POST http://localhost:3000/campaigns

{
    "name": "You must change",
    "content": "change password",
    "emails": ["luazardo@teste.com.br", "luazardo2@teste.com.br","luazardo3@teste.com.br"]

}

###

GET http://localhost:3000/campaigns/csl4gkijivhmjs13h6rg


###

PATCH  http://localhost:3000/campaigns/cancel/csl5da2jivhmv27j8uh0

###
DELETE  http://localhost:3000/campaigns/delete/csl4gkijmjs13h6rg