@url = http://localhost:3000

@identity_provider = http://localhost:8080



POST {{url}}/campaigns
Authorization: Bearer {{access_token}}

{
    "name": "You must change",
    "content": "change password",
    "emails": ["luazardo@teste.com.br", "luazardo2@teste.com.br","luazardo3@teste.com.br"]

}

###
GET {{url}}/campaigns/cslr8gijivhihb6ndu50
Authorization: Bearer {{access_token}}

###
DELETE  {{url}}/campaigns/delete/csl4gkijmjs13h6rg
Authorization: Bearer {{access_token}}

###
PATCH  {{url}}/campaigns/start/csl4gkijmjs13h6rg
Authorization: Bearer {{access_token}}


###
# @name token

POST {{identity_provider}}/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&username=luzardoarruda66@gmail.com&password=123456&grant_type=password
###
@access_token = {{token.response.body.access_token}}